### ISSUE TITLE
Pode testar?

### ISSUE THREAD

**Issue by julianobrasil** [julianobrasil/lib-time-mask#4]
@davidbrahiam, continuando aquela teoria de que talvez seja o pacote errado instalado no seu PC, tente provocar o erro aqui: https://stackblitz.com/edit/angular-timemask-demo

**Comment by davidbrahiam** [comment]
![image](https://user-images.githubusercontent.com/19223755/40153830-fca09ece-5961-11e8-97f5-2e2431524ee8.png)

![image](https://user-images.githubusercontent.com/19223755/40153841-0787ddca-5962-11e8-9de6-5b4db62fafb0.png)


![image](https://user-images.githubusercontent.com/19223755/40153866-215cfd8e-5962-11e8-8f84-4b2abc0074b1.png)

![image](https://user-images.githubusercontent.com/19223755/40153888-3422b332-5962-11e8-92ce-79d6a206c18e.png)


a sequencia de comandos é a mesma que a do issue do sar-front

**Comment by julianobrasil** [comment]
Modifique um pouco, teste aí novamente, por favor.

**Comment by julianobrasil** [comment]
Pode fazer um último teste? https://stackblitz.com/edit/angular-timemask-demo

Se der certo eu faço a versão final (aí no stackblitz está a 1.0.0-beta.0).
